FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /rpcserver ./cmd/rpcserver/main.go

FROM alpine:latest
WORKDIR /
COPY --from=builder /rpcserver .
CMD ["/rpcserver"]